In [2]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# Задача 44\n",
        "В ячейке ниже представлен код генерирующий <u>_DataFrame_</u>, которая состоит всего из 1 столбца. Ваша задача перевести его в <u>_one hot_</u> вид. Сможете ли вы это сделать без <u>_get_dummies_</u>?\n",
        "```python\n",
        "import random  \n",
        "lst = ['robot'] * 10  \n",
        "lst += ['human'] * 10  \n",
        "random.shuffle(lst)  \n",
        "data = pd.DataFrame({'whoAmI':lst})  \n",
        "data.head()\n",
        "```\n"
      ],
      "metadata": {
        "id": "5ncYb6vv7OwX"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import random \n",
        "lst = ['robot'] * 10  \n",
        "lst += ['human'] * 10  \n",
        "random.shuffle(lst)  \n",
        "data = pd.DataFrame({'whoAmI':lst})\n",
        "data.head(10)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 363
        },
        "id": "BOnAgQhH8ds1",
        "outputId": "0c3616f7-ee88-4aa5-f4da-dbf93fcbc08b"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "  whoAmI\n",
              "0  robot\n",
              "1  human\n",
              "2  human\n",
              "3  human\n",
              "4  human\n",
              "5  robot\n",
              "6  robot\n",
              "7  robot\n",
              "8  robot\n",
              "9  human"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-c2e188bf-d9a4-4d61-947b-a6abde79c965\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>whoAmI</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>robot</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>human</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>human</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>human</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>human</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>robot</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>robot</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>robot</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>robot</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>human</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-c2e188bf-d9a4-4d61-947b-a6abde79c965')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-c2e188bf-d9a4-4d61-947b-a6abde79c965 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-c2e188bf-d9a4-4d61-947b-a6abde79c965');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 2
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Метод get_dummies\n",
        "pd.get_dummies(data['whoAmI']).head(10)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 363
        },
        "id": "HYrILFx-9WE7",
        "outputId": "ed840b1f-3d7d-4895-9ff1-46cc14c8442c"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   human  robot\n",
              "0      0      1\n",
              "1      1      0\n",
              "2      1      0\n",
              "3      1      0\n",
              "4      1      0\n",
              "5      0      1\n",
              "6      0      1\n",
              "7      0      1\n",
              "8      0      1\n",
              "9      1      0"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-443611a5-cff5-4aa5-b25a-1a2af58681cd\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>human</th>\n",
              "      <th>robot</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-443611a5-cff5-4aa5-b25a-1a2af58681cd')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-443611a5-cff5-4aa5-b25a-1a2af58681cd button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-443611a5-cff5-4aa5-b25a-1a2af58681cd');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 3
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Без метода get_dummies\n",
        "pd.DataFrame({'human': data['whoAmI'] == 'human',\n",
        "              'robot': data['whoAmI'] == 'robot'}).astype(int).head(10)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 363
        },
        "id": "i8SCUq5x-fz_",
        "outputId": "ea88d08d-28e5-4231-8f0b-c98600b30cc0"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   human  robot\n",
              "0      0      1\n",
              "1      1      0\n",
              "2      1      0\n",
              "3      1      0\n",
              "4      1      0\n",
              "5      0      1\n",
              "6      0      1\n",
              "7      0      1\n",
              "8      0      1\n",
              "9      1      0"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-8d4451b6-f4d5-4d74-85f0-e494890ca370\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>human</th>\n",
              "      <th>robot</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-8d4451b6-f4d5-4d74-85f0-e494890ca370')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-8d4451b6-f4d5-4d74-85f0-e494890ca370 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-8d4451b6-f4d5-4d74-85f0-e494890ca370');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 4
        }
      ]
    }
  ]
}

{'nbformat': 4,
 'nbformat_minor': 0,
 'metadata': {'colab': {'provenance': []},
  'kernelspec': {'name': 'python3', 'display_name': 'Python 3'},
  'language_info': {'name': 'python'}},
 'cells': [{'cell_type': 'markdown',
   'source': ['# Задача 44\n',
    'В ячейке ниже представлен код генерирующий <u>_DataFrame_</u>, которая состоит всего из 1 столбца. Ваша задача перевести его в <u>_one hot_</u> вид. Сможете ли вы это сделать без <u>_get_dummies_</u>?\n',
    '```python\n',
    'import random  \n',
    "lst = ['robot'] * 10  \n",
    "lst += ['human'] * 10  \n",
    'random.shuffle(lst)  \n',
    "data = pd.DataFrame({'whoAmI':lst})  \n",
    'data.head()\n',
    '```\n'],
   'metadata': {'id': '5ncYb6vv7OwX'}},
  {'cell_type': 'code',
   'source': ['import pandas as pd\n',
    'import random \n',
    "lst = ['robot'] * 10  \n",
    "lst += ['human'] * 10  \n",
    'random.shuffle(lst)  \n',
    "data = pd.DataFrame({'whoAmI':lst})\n",
    'data.head(10)'],
   'metadata': {'colab': {'base_uri': 'https://localhost:8080/',
     'height': 363},
    'id': 'BOnAgQhH8ds1',
    'outputId': '0c3616f7-ee88-4aa5-f4da-dbf93fcbc08b'},
   'execution_count': 2,
   'outputs': [{'output_type': 'execute_result',
     'data': {'text/plain': ['  whoAmI\n',
       '0  robot\n',
       '1  human\n',
       '2  human\n',
       '3  human\n',
       '4  human\n',
       '5  robot\n',
       '6  robot\n',
       '7  robot\n',
       '8  robot\n',
       '9  human'],
      'text/html': ['\n',
       '  <div id="df-c2e188bf-d9a4-4d61-947b-a6abde79c965">\n',
       '    <div class="colab-df-container">\n',
       '      <div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>whoAmI</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>0</th>\n',
       '      <td>robot</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>1</th>\n',
       '      <td>human</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>2</th>\n',
       '      <td>human</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>3</th>\n',
       '      <td>human</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>4</th>\n',
       '      <td>human</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>5</th>\n',
       '      <td>robot</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>6</th>\n',
       '      <td>robot</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>7</th>\n',
       '      <td>robot</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>8</th>\n',
       '      <td>robot</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>9</th>\n',
       '      <td>human</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>\n',
       '      <button class="colab-df-convert" onclick="convertToInteractive(\'df-c2e188bf-d9a4-4d61-947b-a6abde79c965\')"\n',
       '              title="Convert this dataframe to an interactive table."\n',
       '              style="display:none;">\n',
       '        \n',
       '  <svg xmlns="http://www.w3.org/2000/svg" height="24px"viewBox="0 0 24 24"\n',
       '       width="24px">\n',
       '    <path d="M0 0h24v24H0V0z" fill="none"/>\n',
       '    <path d="M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z"/><path d="M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z"/>\n',
       '  </svg>\n',
       '      </button>\n',
       '      \n',
       '  <style>\n',
       '    .colab-df-container {\n',
       '      display:flex;\n',
       '      flex-wrap:wrap;\n',
       '      gap: 12px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert {\n',
       '      background-color: #E8F0FE;\n',
       '      border: none;\n',
       '      border-radius: 50%;\n',
       '      cursor: pointer;\n',
       '      display: none;\n',
       '      fill: #1967D2;\n',
       '      height: 32px;\n',
       '      padding: 0 0 0 0;\n',
       '      width: 32px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert:hover {\n',
       '      background-color: #E2EBFA;\n',
       '      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n',
       '      fill: #174EA6;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert {\n',
       '      background-color: #3B4455;\n',
       '      fill: #D2E3FC;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert:hover {\n',
       '      background-color: #434B5C;\n',
       '      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n',
       '      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n',
       '      fill: #FFFFFF;\n',
       '    }\n',
       '  </style>\n',
       '\n',
       '      <script>\n',
       '        const buttonEl =\n',
       "          document.querySelector('#df-c2e188bf-d9a4-4d61-947b-a6abde79c965 button.colab-df-convert');\n",
       '        buttonEl.style.display =\n',
       "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
       '\n',
       '        async function convertToInteractive(key) {\n',
       "          const element = document.querySelector('#df-c2e188bf-d9a4-4d61-947b-a6abde79c965');\n",
       '          const dataTable =\n',
       "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
       '                                                     [key], {});\n',
       '          if (!dataTable) return;\n',
       '\n',
       "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
       '            \'<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>\'\n',
       "            + ' to learn more about interactive tables.';\n",
       "          element.innerHTML = '';\n",
       "          dataTable['output_type'] = 'display_data';\n",
       '          await google.colab.output.renderOutput(dataTable, element);\n',
       "          const docLink = document.createElement('div');\n",
       '          docLink.innerHTML = docLinkHtml;\n',
       '          element.appendChild(docLink);\n',
       '        }\n',
       '      </script>\n',
       '    </div>\n',
       '  </div>\n',
       '  ']},
     'metadata': {},
     'execution_count': 2}]},
  {'cell_type': 'code',
   'source': ['# Метод get_dummies\n',
    "pd.get_dummies(data['whoAmI']).head(10)"],
   'metadata': {'colab': {'base_uri': 'https://localhost:8080/',
     'height': 363},
    'id': 'HYrILFx-9WE7',
    'outputId': 'ed840b1f-3d7d-4895-9ff1-46cc14c8442c'},
   'execution_count': 3,
   'outputs': [{'output_type': 'execute_result',
     'data': {'text/plain': ['   human  robot\n',
       '0      0      1\n',
       '1      1      0\n',
       '2      1      0\n',
       '3      1      0\n',
       '4      1      0\n',
       '5      0      1\n',
       '6      0      1\n',
       '7      0      1\n',
       '8      0      1\n',
       '9      1      0'],
      'text/html': ['\n',
       '  <div id="df-443611a5-cff5-4aa5-b25a-1a2af58681cd">\n',
       '    <div class="colab-df-container">\n',
       '      <div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>human</th>\n',
       '      <th>robot</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>0</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>1</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>2</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>3</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>4</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>5</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>6</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>7</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>8</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>9</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>\n',
       '      <button class="colab-df-convert" onclick="convertToInteractive(\'df-443611a5-cff5-4aa5-b25a-1a2af58681cd\')"\n',
       '              title="Convert this dataframe to an interactive table."\n',
       '              style="display:none;">\n',
       '        \n',
       '  <svg xmlns="http://www.w3.org/2000/svg" height="24px"viewBox="0 0 24 24"\n',
       '       width="24px">\n',
       '    <path d="M0 0h24v24H0V0z" fill="none"/>\n',
       '    <path d="M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z"/><path d="M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z"/>\n',
       '  </svg>\n',
       '      </button>\n',
       '      \n',
       '  <style>\n',
       '    .colab-df-container {\n',
       '      display:flex;\n',
       '      flex-wrap:wrap;\n',
       '      gap: 12px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert {\n',
       '      background-color: #E8F0FE;\n',
       '      border: none;\n',
       '      border-radius: 50%;\n',
       '      cursor: pointer;\n',
       '      display: none;\n',
       '      fill: #1967D2;\n',
       '      height: 32px;\n',
       '      padding: 0 0 0 0;\n',
       '      width: 32px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert:hover {\n',
       '      background-color: #E2EBFA;\n',
       '      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n',
       '      fill: #174EA6;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert {\n',
       '      background-color: #3B4455;\n',
       '      fill: #D2E3FC;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert:hover {\n',
       '      background-color: #434B5C;\n',
       '      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n',
       '      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n',
       '      fill: #FFFFFF;\n',
       '    }\n',
       '  </style>\n',
       '\n',
       '      <script>\n',
       '        const buttonEl =\n',
       "          document.querySelector('#df-443611a5-cff5-4aa5-b25a-1a2af58681cd button.colab-df-convert');\n",
       '        buttonEl.style.display =\n',
       "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
       '\n',
       '        async function convertToInteractive(key) {\n',
       "          const element = document.querySelector('#df-443611a5-cff5-4aa5-b25a-1a2af58681cd');\n",
       '          const dataTable =\n',
       "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
       '                                                     [key], {});\n',
       '          if (!dataTable) return;\n',
       '\n',
       "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
       '            \'<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>\'\n',
       "            + ' to learn more about interactive tables.';\n",
       "          element.innerHTML = '';\n",
       "          dataTable['output_type'] = 'display_data';\n",
       '          await google.colab.output.renderOutput(dataTable, element);\n',
       "          const docLink = document.createElement('div');\n",
       '          docLink.innerHTML = docLinkHtml;\n',
       '          element.appendChild(docLink);\n',
       '        }\n',
       '      </script>\n',
       '    </div>\n',
       '  </div>\n',
       '  ']},
     'metadata': {},
     'execution_count': 3}]},
  {'cell_type': 'code',
   'source': ['# Без метода get_dummies\n',
    "pd.DataFrame({'human': data['whoAmI'] == 'human',\n",
    "              'robot': data['whoAmI'] == 'robot'}).astype(int).head(10)"],
   'metadata': {'colab': {'base_uri': 'https://localhost:8080/',
     'height': 363},
    'id': 'i8SCUq5x-fz_',
    'outputId': 'ea88d08d-28e5-4231-8f0b-c98600b30cc0'},
   'execution_count': 4,
   'outputs': [{'output_type': 'execute_result',
     'data': {'text/plain': ['   human  robot\n',
       '0      0      1\n',
       '1      1      0\n',
       '2      1      0\n',
       '3      1      0\n',
       '4      1      0\n',
       '5      0      1\n',
       '6      0      1\n',
       '7      0      1\n',
       '8      0      1\n',
       '9      1      0'],
      'text/html': ['\n',
       '  <div id="df-8d4451b6-f4d5-4d74-85f0-e494890ca370">\n',
       '    <div class="colab-df-container">\n',
       '      <div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>human</th>\n',
       '      <th>robot</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>0</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>1</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>2</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>3</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>4</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>5</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>6</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>7</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>8</th>\n',
       '      <td>0</td>\n',
       '      <td>1</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>9</th>\n',
       '      <td>1</td>\n',
       '      <td>0</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>\n',
       '      <button class="colab-df-convert" onclick="convertToInteractive(\'df-8d4451b6-f4d5-4d74-85f0-e494890ca370\')"\n',
       '              title="Convert this dataframe to an interactive table."\n',
       '              style="display:none;">\n',
       '        \n',
       '  <svg xmlns="http://www.w3.org/2000/svg" height="24px"viewBox="0 0 24 24"\n',
       '       width="24px">\n',
       '    <path d="M0 0h24v24H0V0z" fill="none"/>\n',
       '    <path d="M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z"/><path d="M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z"/>\n',
       '  </svg>\n',
       '      </button>\n',
       '      \n',
       '  <style>\n',
       '    .colab-df-container {\n',
       '      display:flex;\n',
       '      flex-wrap:wrap;\n',
       '      gap: 12px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert {\n',
       '      background-color: #E8F0FE;\n',
       '      border: none;\n',
       '      border-radius: 50%;\n',
       '      cursor: pointer;\n',
       '      display: none;\n',
       '      fill: #1967D2;\n',
       '      height: 32px;\n',
       '      padding: 0 0 0 0;\n',
       '      width: 32px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert:hover {\n',
       '      background-color: #E2EBFA;\n',
       '      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n',
       '      fill: #174EA6;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert {\n',
       '      background-color: #3B4455;\n',
       '      fill: #D2E3FC;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert:hover {\n',
       '      background-color: #434B5C;\n',
       '      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n',
       '      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n',
       '      fill: #FFFFFF;\n',
       '    }\n',
       '  </style>\n',
       '\n',
       '      <script>\n',
       '        const buttonEl =\n',
       "          document.querySelector('#df-8d4451b6-f4d5-4d74-85f0-e494890ca370 button.colab-df-convert');\n",
       '        buttonEl.style.display =\n',
       "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
       '\n',
       '        async function convertToInteractive(key) {\n',
       "          const element = document.querySelector('#df-8d4451b6-f4d5-4d74-85f0-e494890ca370');\n",
       '          const dataTable =\n',
       "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",